build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true

filter:
    paths:
        - app/*
    excluded_paths:
        - 'scenario/*'
        - 'tmp/*'

checks:
    php:
      code_rating: true
      duplication: true





